### PR TITLE
\href header

### LINKED ISSUE #27: jumpingrivers.com in header should link to jr homepage
Now that we distribute notes digitally more frequently I think that "jumpingrivers.com" in the page header should be a hyperlink to the jr homepage.

### PR DESCRIPTION
**Pull request by jwalton3141**
Closes #27 using `fancyhdr`

### CODE REVIEW

**Comment by csgillespie** [comment]
Looks OK, but I'll need to check it once #28 is done.

**Comment by jwalton3141** [comment]
Yep. I think the only conflict should be in `NEWS.md`

**Comment by csgillespie** [comment]
Other conflicts will be the version number (you'll need to bump) and also the importFrom stringr stuff might be in conflict

**Comment by csgillespie** [comment]
Looks good. But the logo on the front page points to http://www.jr.com (not https)> Can you fix that as well?

**Comment by jwalton3141** [comment]
Yep and  done. Just waiting on travis

**Review by csgillespie — APPROVED** [review]

**Pull request merged**
