### PR TITLE
Spell checks per course

### LINKED ISSUE #40: WORDLIST per course
As suggested by @csgillespie in #36

Each course should have its own separate WORDLIST

### PR DESCRIPTION
**Pull request by csgillespie**
**Main Change**

1. Each course should have it's spell check - the inst/WORDLIST file was now unmanageable
2. Potential spelling issues now raise an error (everyone ignored the `msg_info()` so spelling mistakes weren't fixed)
3. The `inst/WORDLIST` file in jrNotes still exists, but it is much smaller and only contains standard words, e.g. LaTeX and R packages
4. Each course can have it's own WORDLIST file to supplement jrNotes inst/WORDLIST
5. I decided the course WORDLIST should live in the root dir, as it may(?) be used in slides/ or live/ at some point in the future.
6. Fixes #40 

You can test this change by installing the package 
```
remotes::install_github("jr-packages/jrNotes@spelling")
```
Then running
```
Rscript -e "jrNotes::check_spelling()`
```
in course notes repos.

**Other minor changes**

1. Use `{rlang}` instead of dummy variables. It is another important, but since all of `{tidyverse}` depends on it, who cares
2. Fixed the padding when output the potential spelling mistakes
3. Add a `get_root_dir()` function to find the root dir
4. Updated the minimum version of `{rmarkdown}`

### CODE REVIEW

**Comment by trianglegirl** [comment]
`  ℹ Local WORDLIST file not detected
  x A WORDLIST file has been created with potential exceptions.
  x Please check & edit this file carefully.
  x Then add to the WORDLIST file in the root directory`

**Comment by csgillespie** [comment]
@trianglegirl 

1. I've changed the generated file from WORDLIST to `spelling_issues.txt` and improved the feedback (I hope)

**Review by jwalton3141 — APPROVED** [review]
Added some more common tex words to the WORDLIST and some standard python packages. Otherwise looks good to me

**Comment by trianglegirl** [comment]
Can we check the WORDLIST in root is always in alphabetic order? Makes adding new words easier.

**Comment by trianglegirl** [comment]
> @trianglegirl
> 
> 1. I've changed the generated file from WORDLIST to `spelling_issues.txt` and improved the feedback (I hope)
> 2. Not keen on automatically adding words directly to WORDLIST in the root; no-one (including me) will check the words ;)

Looks good. We might want to add `spelling_issues.txt` to make clean to tidy up afterwards.

**Comment by csgillespie** [comment]
@jwalton3141 Thanks for the changes to WORDLIST

@trianglegirl Great suggestions

1. spelling_issues should now be cleaned
2. I now check that `./WORDLIST` is in order, but
  - this means we can have comments (which is fine). We could extend the code to order within comments, but ...
  - To keep the code simpler, if WORDLIST isn't in order, I don't do a spell check. This is mildly annoying, but it made things much easier. I started to run into cases where there were no spelling errors, but the file was out of order. 

Is the above OK?

**Review by trianglegirl — APPROVED** [review]
Yep, all looks sensible.

**Pull request merged**
